name: music_player_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.0-44.1.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  audio_video_progress_bar: ^0.10.0
  
  filesize: ^2.0.1
  flutter_launcher_icons: ^0.9.3
  flutter_screenutil: ^5.5.3+2
  font_awesome_flutter: ^10.1.0
  google_nav_bar: ^5.0.6
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  just_audio: ^0.9.24
  just_audio_background: ^0.0.1-beta.5
  on_audio_query: ^2.6.1
  path_provider: ^2.0.11
  rxdart: ^0.27.4
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.3  


  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  hive_generator: ^1.1.3
  rflutter_alert: ^2.0.4

  
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/icon.jpg"


flutter:


  uses-material-design: true
  assets:
    - lib/assets/images/IMG_0007.JPG
    - lib/assets/images/icon.jpg

  